### ISSUE TITLE
Unable to use this AsyncEx with NetStandard Profile

### ISSUE THREAD

**Issue by milanio** [StephenCleary/AsyncEx.Tasks#3]
When you try to use Nuget package in a PCL library which targets NetStandard 1.2 I get "Nito.AsyncEx 3.0.1 is not compatible with .NETStandard,Version=v1.2."

Is there any chance this library will support .NETStandard,Version=v1.2 or any version of .NETStandard for that matter? 

As I needed to use this library I was forced to create a fork and recompile against .NetStandard v 1.2. and it seems to be working fine so it seems the issue is only a matter of packaging.

**Comment by StephenCleary** [comment]
Moving this issue to the AsyncEx project.
