### ISSUE TITLE
.NET Standard 1.2 Support 

### ISSUE THREAD

**Issue by inforithmics** [StephenCleary/AsyncEx.Tasks#4]
I have a project that builds with .NET Standard 1.2 But I cannot use AsyncEx.Tasks because it targets 1.2 Is there a possibility to change that?

The reason I target it is because i support windows 8.1 (WinRt ) Apps with this library

**Comment by StephenCleary** [comment]
No; all of the netstandard AsyncEx libraries already target the lowest version they can.

This is following Microsoft's lead - they don't support Win81 with their modern tooling, either. Note the following quote from the [Visual Studio 2017 Compatibility page](https://www.visualstudio.com/en-us/productinfo/vs2017-compatibility-vs):

> Projects for Windows Store 8.1 and 8.0, and Windows Phone 8.1 and 8.0 are not supported in this release. To maintain these apps, continue to use Visual Studio 2015.

Long term (i.e., in a few years), you'll need to drop Win81 support and change to Win10. Win10 is the replacement for Win81, and UAP is the replacement for WinRT.

In the meantime, you can use [`Nito.AsyncEx` version 4](http://www.nuget.org/packages/Nito.AsyncEx/4.0.1). It is in maintenance mode - bugfixes only, no new features. But it does support Win81.
